name:                haskell-study
version:             0.1.0.0
github:              "kolov/haskell-study"
license:             BSD3
author:              "Assen Kolov"
maintainer:          "assen.kolov@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/koloc/haskell-study#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- QuickCheck

library:
  source-dirs: src

executables:
  haskell-study-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-study

tests:
  haskell-study-test:
    main:                Chapter15MonoidSpec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-study
